name: Submodule Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Check-Submodule-Commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: true
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Check submodule
        run: |
          PR_BRANCH=`jq -r ".pull_request.head.ref" "${GITHUB_EVENT_PATH}"`
          BASE_BRANCH=`jq -r ".pull_request.base.ref" "${GITHUB_EVENT_PATH}"`
          PR_HEAD=`git rev-parse origin/${PR_BRANCH}`
          MERGE_BASE=`git merge-base origin/${BASE_BRANCH} origin/${PR_BRANCH}`
          SUB_DIFF=`git diff ${MERGE_BASE} ${PR_HEAD} vehicle_sim`
          if [[ ! -z "$SUB_DIFF" ]]; then
            cd vehicle_sim
            SUB_PR_HEAD=`git rev-parse HEAD`
            SUB_MERGE_BASE_HEAD=`git rev-parse origin/main`
            if [ "${SUB_PR_HEAD}" != "${SUB_MERGE_BASE_HEAD}" ]; then
              echo "::error file=vehicle_sim::submodule not up to date"
              exit 1
            fi
          fi
